"""Generate compact 1-bit Arial Bold glyph tables for the firmware."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "firmware/config/boards/arm/hw75_dynamic/app/app_font_data.h"
)
FONT_PATH = r"C:\Windows\Fonts\arialbd.ttf"
SIZES = (8, 13, 28, 36)


def glyph(font, char):
    box = font.getbbox(char)
    width = max(1, box[2] - box[0])
    height = max(1, box[3] - box[1])
    image = Image.new("L", (width, height), 255)
    draw = ImageDraw.Draw(image)
    draw.text((-box[0], -box[1]), char, font=font, fill=0)
    bits = []
    value = 0
    count = 0
    for pixel in image.getdata():
        value = (value << 1) | (1 if pixel < 128 else 0)
        count += 1
        if count == 8:
            bits.append(value)
            value = 0
            count = 0
    if count:
        bits.append(value << (8 - count))
    return width, height, max(1, round(font.getlength(char))), bits


def main():
    lines = [
        "/* Generated by tools/generate_firmware_fonts.py. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "\tuint16_t offset;",
        "\tuint8_t width;",
        "\tuint8_t height;",
        "\tuint8_t advance;",
        "} app_font_glyph_t;",
        "",
        "typedef struct {",
        "\tconst app_font_glyph_t *glyphs;",
        "\tconst uint8_t *bitmap;",
        "} app_font_t;",
        "",
    ]
    for size in SIZES:
        font = ImageFont.truetype(FONT_PATH, size)
        bitmap = []
        descriptors = []
        for code in range(32, 96):
            width, height, advance, data = glyph(font, chr(code))
            descriptors.append((len(bitmap), width, height, advance))
            bitmap.extend(data)

        lines.append(f"static const app_font_glyph_t app_font_{size}_glyphs[64] = {{")
        for offset, width, height, advance in descriptors:
            lines.append(f"\t{{{offset}, {width}, {height}, {advance}}},")
        lines.append("};")
        lines.append(f"static const uint8_t app_font_{size}_bitmap[] = {{")
        for start in range(0, len(bitmap), 16):
            chunk = ", ".join(f"0x{x:02x}" for x in bitmap[start:start + 16])
            lines.append(f"\t{chunk},")
        lines.append("};")
        lines.append(
            f"static const app_font_t app_font_{size} = "
            f"{{app_font_{size}_glyphs, app_font_{size}_bitmap}};"
        )
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
